project:
  type: website
  resources: 
    cv/H.Sherry-Zhang.pdf

website:
  title: "H. Sherry Zhang"
  navbar:
    left:
      - index.qmd
      - href: blogs/index.qmd
        text: Blog

format:
  html:
    theme: sandstone
    css: styles.scss
    toc: true

editor: visual

