project:
  type: website
  resources: 
    cv/H.Sherry-Zhang.pdf

website:
  title: "H. Sherry Zhang"
  sidebar: false
  site-url: https://huizezhangsh.netlify.app/
  repo-url: https://github.com/huizezhang-sherry/sherry
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: blogs/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/huizezhang-sherry
        aria-label: GitHub
  favicon: avatar.jpeg

format:
  html:
    theme: 
      - sandstone
      - style.scss
    toc: false

editor: source

