project:
  type: website
  resources:
    - sherry-zhang.pdf

website:
  title: "H. Sherry Zhang"
  navbar:
    left:
      - index.qmd
      - href: blogs/index.qmd
        text: Blog

format:
  html:
    theme: sandstone
    css: styles.scss
    toc: true

editor: visual

