---
name: H. Sherry Zhang
www: huizezhangsh.netlify.app
address: "Last updated on `r format(Sys.time(), '%B, %Y')`"
email: "Huize.Zhang@monash.edu"
twitter: huizezhangsh
github: huizezhang-sherry
output: 
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
# render with rmarkdown::render(here::here("cv/H.Sherry-Zhang.rmd"), "vitae::awesomecv") 
```

# Education

```{r}
library(tibble)
# changed \setlength\tabcolsep{5pt}% in line 613 of awesome-cv.cls
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ details,
  
  "Doctor of Philosophy", "Feb 2020 - Aug 2023", "Monash University", "Melbourne, Australia","Thesis: New tools for visualising and explaining multivariate spatio-temporal data, supervised by Dianne Cook, Patricia Menéndez, Nicolas Langrené (BNU-HKBU United International College, China), and Ursula Laa (BOKU, Austria)",
  
  
  
  "Bachelor of Commerce (Honours), Econometrics & Business Analytics", "Feb 2016 - Dec 2019", "Monash University", "Melbourne, Australia", "First Class Honours (H1)",
  "Bachelor of Commerce (Honours), Econometrics & Business Analytics", "Feb 2016 - Dec 2019", "Monash University", "Melbourne, Australia", "Thesis: Exploration of judicial facial expression in videos of legal proceedings, supervised by Dianne Cook and Russell Smyth"
) %>% 
  detailed_entries(Degree, Year, Institution, Where, details)
```

# Publications

```{r}
bibliography_entries(here::here("cv/pub.bib"))
# tribble(
#   ~num, ~when, ~paper,
#   "1. ", " ", "Zhang, H. S., Cook, D., Laa, U., Langrené, N., & Menéndez, P. (2021). Visual diagnostics for constrained optimisation with application to guided tours. arXiv Preprint arXiv:2104.03448.",
#   "2. ", " ", "Lee, S., Cook, D., Da Silva, N., Laa, U., Wang, E., Spyrison, N., & Zhang, H. S. (2021). A review of the state‐of‐
# the‐art on tours for dynamic visualization of high‐dimensional data. arXiv Preprint arXiv:2104.08016."
# ) %>% 
#   brief_entries(paper, num, when)
```

# Talks

```{r conf}
tribble(
  ~ conf, ~ date, ~ where, ~ topic, ~ link, ~content,
  
  "Research Tools Workshop", "Sept 2023", "Monash University", " ", "https://sherryzhang-quarto2023.netlify.app/", "",
  
  "Visiting talk", "May 2023", "University of Münster, Germany", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-germany2023.netlify.app/", "",
  
  "Visiting talk", "Apr 2023", "Maynooth University, Ireland", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-ireland2023.netlify.app/", "",
  
  "The Australia Spatial Econometrics \\& Statistics Workshop", "Feb 2023 \\newline", "Monash University \\newline", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-monashspatial2023.netlify.app/", "\\newline targeted audience in econometrics and statistics",
  
  "ECSS Miniconference", "Nov 2022", "virtual", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-ecssmini2022.netlify.app/", "\\newline People's Choice Award",
  
  "CANSSI Ontario Statistics Software Conference (invited)", "Nov 2022 \\newline", "virtual \\newline", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-canssi2022.netlify.app/", "",
  
  "UseR! 2022", "Jun 2022", "virtual", "Cubble: An R package for organizing and wrangling multivariate spatio-temporal data", "https://sherryzhang-user2022.netlify.app/", "",
  
  "UseR! 2021", "Jul 2021", "virtual", "Visual diagnostics for constrained optimisation with application to guided tours", "https://sherryzhang-user2021.netlify.app/", "") %>%
  brief_entries(what = glue::glue("\\strong{<conf>}: \\url{<link>}", .open = "<", .close = ">"), when = date, with = where, .protect = FALSE)

```

# Teaching

<!-- \footnotesize I have been the teaching associate for various units in Monash Master of Business Analytics program and have teaching evaluation score constantly over 4.5 (out of 5). My responsibilities involve lab supervision, tutorial delivery, marking assignments, and unit admin tasks. -->

```{r tutoring}
tribble(
  ~ uni, ~ dates, ~ details, ~ content, ~url,
  "Monash University",  "Sem 1 \\newline 20 \\& 21", "ETC5512 Wild Caught Data",
  "on wrangling open data into analysis ready shape through case study on US air traffic data, Australia census and election data, among others", "https://wcd.numbat.space/",
  "Monash University",  "Sem 2 \\newline 20 \\& 21", "ETC5521 Exploratory Data Analysis", 
  "project-based exploratory data analysis class", "https://eda.numbat.space/",
  "Monash University", "Sem 1 20 \\newline Sem 2 19 ", "ETC1010/ETC5510 Introduction to Data Analysis",
  "on introducing tidyverse tools for data wrangling \\& visualising, basics in web scraping, text analysis, and programming with R", "https://ida.numbat.space/"
) %>% 
  brief_entries(what = glue::glue("\\strong{<details>}\\space \\url{<url>}\\newline \\em{<content>}", .open = "<", .close = ">"), when = paste0(dates, "\\newline"), with = paste0(uni, "\\newline"), .protect = FALSE) 
```

# Workshop

```{r workshop}
tribble(
  ~ conf, ~ date, ~ where, ~ topic, ~ link,
  
   "R Ladies Vienna \\newline", "Apr 2023 \\newline", "onsite", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-rladiesvienna2023.netlify.app/",
  
  "WOMBAT", "Dec 2022", "aaa", "Wrangling spatio-temporal data with R", "https://sptm-tidy.numbat.space/",
  
  "R Ladies Melbourne \\newline", "Sept 2022 \\newline", "onsite", "Switching between space and time: Spatio-temporal analysis with cubble", "https://sherryzhang-rladiesmelb2022.netlify.app/") %>%
  brief_entries(what = glue::glue("\\strong{<topic>}\\space\\url{<link>}", .open = "<", .close = ">"), when = paste0(date), with = conf, .protect = FALSE)
```

# Software

<!-- \footnotesize I contributes to open source software, available on the Comprehensive R Archive Network (CRAN) and Github. -->

```{r r-pkgs}
tribble(
  ~ pkg, ~ when, ~ role, ~ details, ~ url,
  "cubble", "2022 -", "author", "a multivariate data structure for organizing and wrangling spatio-temporal data","https://cran.r-project.org/web/packages/cubble/index.html",
  "rjtools", "2021 -", "contributor", "tools for authors to write, check, and submit articles to the R Journal", "https://github.com/rjournal/rjtools",
  "rj", "2021 -", "contributor", "tools to help the (associate) editors with the reviewing process of the R journal", "https://github.com/rjournal/rj",
  "ferrn", "2021 -", "author", "a package for visual diagnostics of projection pursuit guided tour optimisation", "https://cran.r-project.org/web/packages/ferrn/index.html",
  "tourr", "2020 -", "contributor", "implementing a data structure for collecting guided tour optimistaion data", "https://cran.r-project.org/web/packages/tourr/index.html"
) %>% 
  brief_entries(glue::glue("\\textbf{<pkg>}: <details>\\newline \\url{<url>}" , .open = "<", .close = ">"), when = paste0(when, "\\newline"), .protect = FALSE)
```

# Awards

```{r}
tribble(
  ~ grants, ~ dates, ~ where,
  "Opportunity scholar", "2023", "Posit::conf(2023)",
  "People's Choice Award for the presentation in ECSS Miniconference", "2022", "Statistical Society of Australia",
  "Postgraduate (PhD) Research Scholarship ", "20 - 23", "CSIRO Data61",
  "Co-Funded Graduate Research Scholarship ", " 20 - 23", "Monash Business School",
  "Dean's Honours List", "2020", "Monash Business School",
  "Summer Vacation Research Scholarship", "2019", "Monash University") %>% 
  brief_entries(glue::glue("<grants>", .open = "<", .close = ">"), dates, where)
```

# Affiliation

```{r affi}
tribble(
  ~ affi, ~date,
  "Non-Uniform Monash Business Analytics Team (Monash NUMBATs)", "1. ",
  "Statistical Society of Australia (VIC branch)", "2. ",
  #"Australian Research Council Centre of Excellence in Mathematical and Statistical Frontiers", "3. ",
  "Commonwealth Scientific and Industrial Research Organisation (CSIRO) Data61", "3. "
) %>%
  brief_entries(affi, date)
```

# Service

```{r}
tribble(
  ~ date, ~position, ~content,
  2022, "Monash NUMBATs seminar organiser", "https://numbat.space/"
) %>% 
  brief_entries(glue::glue("<position>: \\url{<content>}", .open = "<", .close = ">"), date,
                .protect = FALSE)
```
