---
title: "Visual Diagnostics for Constrained Optimisation with Application to Guided Tours"
date: "2021-11-20T17:03:00+10:00"
publication: "R Journal"
authors: []
tags: []
categories: []
featured: false
draft: false

url_pdf: https://journal.r-project.org/archive/2021/RJ-2021-105/index.html
url_project: https://github.com/huizezhang-sherry/paper-ferrn
url_code: https://github.com/huizezhang-sherry/ferrn
---

A guided tour helps to visualise high-dimensional data by showing low-dimensional projec tions along a projection pursuit optimisation path. Projection pursuit is a generalisation of principal component analysis in the sense that different indexes are used to define the interestingness of the projected data. While much work has been done in developing new indexes in the literature, less has been done on understanding the optimisation. Index functions can be noisy, might have multiple local maxima as well as an optimal maximum, and are constrained to generate orthonormal projection frames, which complicates the optimization. In addition, projection pursuit is primarily used for exploratory data analysis, and finding the local maxima is also useful. The guided tour is especially useful for exploration because it conducts geodesic interpolation connecting steps in the optimisation and shows how the projected data changes as a maxima is approached. This work provides new visual diagnostics for examining a choice of optimisation procedure based on the provision of a new data object which collects information throughout the optimisation. It has helped to diagnose and fix several problems with projection pursuit guided tour. This work might be useful more broadly for diagnosing optimisers and comparing their performance. The diagnostics are implemented in the R package ferrn.
